language: go
go:
  - 1.12.x

os:
  - linux

services:
  - docker

dist: trusty
sudo: false

install: true

env:
  - GO111MODULE=on

script:
  - go test -v
notifications:
  slack: geigsen2:TBhXpLjpz2ggwaNWOTcO7TSo
